config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% form.label :first_name, style: "display: block" %>
    <br/>
    <%= form.text_field :first_name , class:"form-control" ,placeholder:"First Name" %>
  </div>

  <div>
    <% form.label :last_name, style: "display: block" %>
    <br/>
    <%= form.text_field :last_name , class:"form-control",placeholder:"Last Name" %>
  </div>

  <div>
    <% form.label :email, style: "display: block" %>
    <br/>
    <%= form.text_field :email ,class:"form-control" ,placeholder:"Email" %>
  </div>

  <div>
    <% form.label :phone, style: "display: block" %>
    <br/>
    <%= form.text_field :phone ,class:"form-control" ,placeholder:"Phone" %>
  </div>

  <div>
    <% form.label :twitter, style: "display: block" %>
    <br/>
    <%= form.text_field :twitter ,class:"form-control" ,placeholder:"Twitter" %>
  </div>

  <div>
    <% form.label :user_id, style: "display: block" %>
    <br/>
    <%= form.number_field :user_id,id: :friend_user_id ,class:"form-control" ,value:current_user.id,type: :hidden %>
  </div>
  

  <br/>
  <div>
    <%= form.submit class:"btn btn-secondary pt"%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div  id="<%= dom_id friend %>" class=" card">
  <div>
    <%= image_tag ("/assets/#{rand(4)}.png"),class:"img-fluid" %>
    <div class="card-body">
      
          <h5 class="card-title">First name:</h5>
          <p class="card-text"><%= friend.first_name %>
        
      
          <h5 class="card-title">Last name:</h5>
          <p class="card-text"><%= friend.last_name %></p>
        

        
          <h5 class="card-title">Email:</h5>
          <p class="card-text"><%= friend.email %></p>
        

        
          <h5 class="card-title">Phone:</h5>
          <p class="card-text"><%= friend.phone %></p>
        

        
          <h5 class="card-title">Twitter:</h5>
          <p class="card-text"><%= friend.twitter %></p>
          
    </div>
  </div>
</div>

app/views/friends/edit.html.erb
<br/>
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend , class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<div class="container p">


<h1>Friends List</h1>

<div id="friends" class="d-md-flex flex-wrap justify-content-around">
  <% @friends.each do |friend| %>
    <div>
      <%= render friend %>
      <%= link_to "Show this friend", friend ,class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

<%= link_to "New friend", new_friend_path ,class:"btn btn-secondary m" %>
</div>

app/views/friends/new.html.erb
<br/>
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<div class="container ">

<div class="d-md-flex flex-wrap justify-content-around">
  <%= render @friend %>
</div>

  <%# this page needs some custom style %>
  <%# <%= @friend.email%> %>
  
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %> 
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>

  <%= button_to "Destroy this friend", @friend, method: :delete %>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
        

       
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-dark" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br/>
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>hello rails</h1>
this is my first rails page

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FriendsList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %> 

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
    <br/>
      <% if notice %>
        <%= render "layouts/alerts" %>
      <% end %>
      <%= yield %>
    </div>
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>